# Generated by Django 4.1.3 on 2023-05-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_producttag_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('study_level', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('diploma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('demandeur', 'demandeur'), ('salarie', 'salarie'), ('travailleur', 'travailleur'), ('Etudiant', 'Etudiant')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.gallery')),
            ],
        ),
    ]
