# Generated by Django 4.1.3 on 2023-05-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='advantages',
            field=models.TextField(blank=True),
        ),
    ]
