# Generated by Django 4.1.3 on 2023-05-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiement', '0002_offer_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='pole',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
